name: grocery_shopping_app
description: Grocery Shopping App - Flutter Frontend
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^12.1.3
  
  # Networking & JSON
  dio: ^5.3.2
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  
  # UI & Utils
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  flutter_svg: ^2.0.9
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Push Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  
  # Date/Time handling
  intl: ^0.19.0
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Utilities
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.5
  hive_generator: ^2.0.1
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
